server:
  port: 8080

spring:
  profiles:
    active: rbac, ai
  application:
    name: AuraGate
  autoconfigure:
    exclude:
      - com.alibaba.druid.spring.boot3.autoconfigure.DruidDataSourceAutoConfigure
